### PR TITLE
Basiclaly this will add a 7kb image (pretty optimized tbh) of hd emoji bread by google

### PR DESCRIPTION
**Pull request by Theslees**
this is google bread (512x512) :) :+1: 
pls merge

### CODE REVIEW

**Comment by kwzuu** [comment]
not enough bread

**Comment by Theslees** [comment]
:bread: :bread: :bread: :bread:

**Comment by jdadonut** [comment]
not enough bread

**Review by aenriii — CHANGES_REQUESTED** [review]
not enough bread

**Pull request closed without merging**
